version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  django:
    build: ../backend/foodgram/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../backend/foodgram:/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
