# Generated by Django 2.2.16 on 2022-12-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favouriterecipe',
            name='user_recipe_unique',
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='name_measurement_unit_unique',
        ),
        migrations.RemoveConstraint(
            model_name='tag',
            name='name_slug_unique',
        ),
        migrations.AddConstraint(
            model_name='favouriterecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='favourite_user_recipe_unique'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='ingredient_name_measurement_unit_unique'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'slug'), name='tag_name_slug_unique'),
        ),
    ]
