# Generated by Django 2.2.16 on 2022-12-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221211_1710'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[],
        ),
    ]
