# Generated by Django 2.2.16 on 2022-12-19 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221214_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={
                'ordering': ('-id',),
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={
                'ordering': ('-id',),
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
