# Generated by Django 2.2.16 on 2022-12-11 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingOrder',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'recipe_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='shopping_orders',
                        to='recipes.Recipe',
                    ),
                ),
                (
                    'user_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='shopping_orders',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Заказ на покупку',
                'verbose_name_plural': 'Заказы на покупку',
            },
        ),
        migrations.AddConstraint(
            model_name='shoppingorder',
            constraint=models.UniqueConstraint(
                fields=('user_id', 'recipe_id'), name='user_recipe_unique'
            ),
        ),
    ]
