# Generated by Django 2.2.16 on 2022-12-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppingorder',
            name='user_recipe_unique',
        ),
        migrations.AddConstraint(
            model_name='shoppingorder',
            constraint=models.UniqueConstraint(fields=('user_id', 'recipe_id'), name='shopping_order_user_recipe_unique'),
        ),
    ]
