# Generated by Django 2.2.16 on 2022-12-19 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_auto_20221214_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingorder',
            options={
                'ordering': ('-id',),
                'verbose_name': 'Заказ на покупку',
                'verbose_name_plural': 'Заказы на покупку',
            },
        ),
    ]
