# Generated by Django 2.2.16 on 2022-12-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_auto_20221219_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingorder',
            options={
                'ordering': ('-id',),
                'verbose_name': 'Список покупок',
                'verbose_name_plural': 'Списки покупок',
            },
        ),
    ]
